### ISSUE TITLE
校友，加油

### ISSUE THREAD

**Issue by DeSireFire** [wangziyu9/jnu#1]
看到你主页，zzuli这个词的出现，我有点惊讶。
你的头像背景让人熟悉，但是我有点分不清是老区还是新区的了2333
过来打个招呼~

**Comment by wangziyu9** [comment]
谢谢呀，闲来无事搜 zzuli 搜到过你的项目。
刚换的头像，这里是新区北门篮球场中间的广场

**Comment by DeSireFire** [comment]
也对吼，计算机专业好像都是在新区的。我当时是5、6号楼宿舍？就是百度打印那里
